/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Cajon.ConstructorCajonConductor;
import Controladores.ControladorvistaConductor;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.awt.Color;
import java.awt.Font;
import javax.swing.UIManager;
import modelos.EmpresaTransporte;
import modelos.EmpresaTransporteDAO;
import modelos.Personas;
import modelos.PersonasDAO;
import modelos.RegistroConsumos;
import modelos.RegistroConsumosDAO;
import modelos.Rutas;
import modelos.RutasDAO;
import modelos.UnidadDAO;
import modelos.Unidades;
import modelos.Usuarios;
import raven.drawer.Drawer;
import raven.popup.GlassPanePopup;
import uk.co.caprica.vlcj.factory.discovery.provider.DiscoveryProviderPriority;

/**
 *
 * @author abela
 */
public class VistaConductor extends javax.swing.JFrame {

    Personas per = new Personas();
    PersonasDAO perdao = new PersonasDAO();
    private RegistroConsumos registroConsumos;
    private RegistroConsumosDAO registroConsumosDAO;
    private Rutas rutas;
    private RutasDAO rutasDAO;
    private EmpresaTransporte empre;
    private EmpresaTransporteDAO empreDAO;
    private Unidades uni;
    private UnidadDAO unidao;
    private Personas user;

    public VistaConductor() {
        GlassPanePopup.install(this);
        ConstructorCajonConductor constructorCajonConductor = new ConstructorCajonConductor(this);
        Drawer.getInstance().setDrawerBuilder(constructorCajonConductor);
        initComponents();
        init();
    }

    public VistaConductor(String dni) {

        GlassPanePopup.install(this);
        ConstructorCajonConductor constructorCajonConductor = new ConstructorCajonConductor(this);
        Drawer.getInstance().setDrawerBuilder(constructorCajonConductor);
        Personas user = perdao.persona(dni);
        registroConsumosDAO = new RegistroConsumosDAO();
        rutasDAO=new RutasDAO(); 
        initComponents();
        ControladorvistaConductor contro = new ControladorvistaConductor(this, registroConsumos, registroConsumosDAO, rutas, rutasDAO, empre, empreDAO, uni, unidao, user);

        System.out.println("hoa" + user.getNombres());

        jlblnombreusuario.setText(user.getNombres());

        init();

    }

    public void init() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneles = new raven.crazypanel.CrazyPanel();
        pnlConsumos = new raven.crazypanel.CrazyPanel();
        menuConsumos = new Clases.CrazyPanel();
        btnmenu5 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jlblnombreusuario = new javax.swing.JLabel();
        tablaConsumos = new Clases.CrazyPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblconsumosuser = new javax.swing.JTable();
        ConsumoBotones = new Clases.CrazyPanel();
        pnlBotonesBusqueda5 = new Clases.CrazyPanel();
        txtBuscar5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pnlRutas = new raven.crazypanel.CrazyPanel();
        menuRutas = new Clases.CrazyPanel();
        btnmenu6 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        tablaRutas = new Clases.CrazyPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblrutas = new javax.swing.JTable();
        RutasBotones = new Clases.CrazyPanel();
        pnlBotonesBusqueda6 = new Clases.CrazyPanel();
        txtBuscar6 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pnlEmpresas = new raven.crazypanel.CrazyPanel();
        menuEmpresas = new Clases.CrazyPanel();
        btnmenu7 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        tablaEmpresas = new Clases.CrazyPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        EmpresasBotones = new Clases.CrazyPanel();
        pnlBotonesBusqueda7 = new Clases.CrazyPanel();
        txtBuscar7 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pnlUnidades = new raven.crazypanel.CrazyPanel();
        menuUnidades = new Clases.CrazyPanel();
        btnmenu8 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        tablaUnidades = new Clases.CrazyPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        UnidadesBotones = new Clases.CrazyPanel();
        pnlBotonesBusqueda8 = new Clases.CrazyPanel();
        txtBuscar8 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paneles.setLayout(new java.awt.CardLayout(30, 20));

        pnlConsumos.setLayout(new java.awt.BorderLayout());

        menuConsumos.setAlignmentX(1.0F);
        menuConsumos.setPreferredSize(new java.awt.Dimension(100, 80));

        btnmenu5.setBackground(new java.awt.Color(30, 30, 30));
        btnmenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/menu.png"))); // NOI18N
        btnmenu5.setPreferredSize(new java.awt.Dimension(120, 123));
        btnmenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenu5ActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Consumos");
        jLabel26.setAlignmentX(1.0F);
        jLabel26.setPreferredSize(new java.awt.Dimension(262, 40));

        javax.swing.GroupLayout menuConsumosLayout = new javax.swing.GroupLayout(menuConsumos);
        menuConsumos.setLayout(menuConsumosLayout);
        menuConsumosLayout.setHorizontalGroup(
            menuConsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuConsumosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnmenu5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 790, Short.MAX_VALUE)
                .addComponent(jlblnombreusuario)
                .addGap(102, 102, 102))
        );
        menuConsumosLayout.setVerticalGroup(
            menuConsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuConsumosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnmenu5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuConsumosLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(menuConsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblnombreusuario)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlConsumos.add(menuConsumos, java.awt.BorderLayout.PAGE_START);

        tablaConsumos.setPreferredSize(new java.awt.Dimension(1245, 530));

        tblconsumosuser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código de Consumo", "Tarjeta", "Monto de Consumo", "Fecha de Consumo", "Unidad", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblconsumosuser);

        ConsumoBotones.setEnabled(false);
        ConsumoBotones.setPreferredSize(new java.awt.Dimension(900, 216));
        ConsumoBotones.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                ConsumoBotonesComponentAdded(evt);
            }
        });
        ConsumoBotones.setLayout(new java.awt.BorderLayout());

        txtBuscar5.setMinimumSize(new java.awt.Dimension(650, 30));
        txtBuscar5.setPreferredSize(new java.awt.Dimension(450, 30));
        txtBuscar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscar5ActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlBotonesBusqueda5Layout = new javax.swing.GroupLayout(pnlBotonesBusqueda5);
        pnlBotonesBusqueda5.setLayout(pnlBotonesBusqueda5Layout);
        pnlBotonesBusqueda5Layout.setHorizontalGroup(
            pnlBotonesBusqueda5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesBusqueda5Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(txtBuscar5, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(338, Short.MAX_VALUE))
        );
        pnlBotonesBusqueda5Layout.setVerticalGroup(
            pnlBotonesBusqueda5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesBusqueda5Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(pnlBotonesBusqueda5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBuscar5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        ConsumoBotones.add(pnlBotonesBusqueda5, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout tablaConsumosLayout = new javax.swing.GroupLayout(tablaConsumos);
        tablaConsumos.setLayout(tablaConsumosLayout);
        tablaConsumosLayout.setHorizontalGroup(
            tablaConsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ConsumoBotones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1237, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablaConsumosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        tablaConsumosLayout.setVerticalGroup(
            tablaConsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablaConsumosLayout.createSequentialGroup()
                .addComponent(ConsumoBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlConsumos.add(tablaConsumos, java.awt.BorderLayout.CENTER);

        paneles.add(pnlConsumos, "card2");

        pnlRutas.setLayout(new java.awt.BorderLayout());

        menuRutas.setAlignmentX(1.0F);
        menuRutas.setPreferredSize(new java.awt.Dimension(100, 80));

        btnmenu6.setBackground(new java.awt.Color(30, 30, 30));
        btnmenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/menu.png"))); // NOI18N
        btnmenu6.setPreferredSize(new java.awt.Dimension(120, 123));
        btnmenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenu6ActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Rutas");
        jLabel29.setAlignmentX(1.0F);
        jLabel29.setPreferredSize(new java.awt.Dimension(262, 40));

        javax.swing.GroupLayout menuRutasLayout = new javax.swing.GroupLayout(menuRutas);
        menuRutas.setLayout(menuRutasLayout);
        menuRutasLayout.setHorizontalGroup(
            menuRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuRutasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnmenu6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(892, Short.MAX_VALUE))
        );
        menuRutasLayout.setVerticalGroup(
            menuRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuRutasLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(menuRutasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnmenu6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlRutas.add(menuRutas, java.awt.BorderLayout.PAGE_START);

        tablaRutas.setPreferredSize(new java.awt.Dimension(1245, 530));

        tblrutas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID de Ruta", "Nombre de Ruta", "Monto de Ruta", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tblrutas);

        RutasBotones.setEnabled(false);
        RutasBotones.setPreferredSize(new java.awt.Dimension(900, 216));
        RutasBotones.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                RutasBotonesComponentAdded(evt);
            }
        });
        RutasBotones.setLayout(new java.awt.BorderLayout());

        txtBuscar6.setMinimumSize(new java.awt.Dimension(650, 30));
        txtBuscar6.setPreferredSize(new java.awt.Dimension(450, 30));
        txtBuscar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscar6ActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlBotonesBusqueda6Layout = new javax.swing.GroupLayout(pnlBotonesBusqueda6);
        pnlBotonesBusqueda6.setLayout(pnlBotonesBusqueda6Layout);
        pnlBotonesBusqueda6Layout.setHorizontalGroup(
            pnlBotonesBusqueda6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesBusqueda6Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(txtBuscar6, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(395, Short.MAX_VALUE))
        );
        pnlBotonesBusqueda6Layout.setVerticalGroup(
            pnlBotonesBusqueda6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesBusqueda6Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(pnlBotonesBusqueda6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBuscar6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        RutasBotones.add(pnlBotonesBusqueda6, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout tablaRutasLayout = new javax.swing.GroupLayout(tablaRutas);
        tablaRutas.setLayout(tablaRutasLayout);
        tablaRutasLayout.setHorizontalGroup(
            tablaRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RutasBotones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1237, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablaRutasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6)
                .addContainerGap())
        );
        tablaRutasLayout.setVerticalGroup(
            tablaRutasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablaRutasLayout.createSequentialGroup()
                .addComponent(RutasBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlRutas.add(tablaRutas, java.awt.BorderLayout.CENTER);

        paneles.add(pnlRutas, "card2");

        pnlEmpresas.setLayout(new java.awt.BorderLayout());

        menuEmpresas.setAlignmentX(1.0F);
        menuEmpresas.setPreferredSize(new java.awt.Dimension(100, 80));

        btnmenu7.setBackground(new java.awt.Color(30, 30, 30));
        btnmenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/menu.png"))); // NOI18N
        btnmenu7.setPreferredSize(new java.awt.Dimension(120, 123));
        btnmenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenu7ActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Empresas");
        jLabel34.setAlignmentX(1.0F);
        jLabel34.setPreferredSize(new java.awt.Dimension(262, 40));

        javax.swing.GroupLayout menuEmpresasLayout = new javax.swing.GroupLayout(menuEmpresas);
        menuEmpresas.setLayout(menuEmpresasLayout);
        menuEmpresasLayout.setHorizontalGroup(
            menuEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuEmpresasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnmenu7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(892, Short.MAX_VALUE))
        );
        menuEmpresasLayout.setVerticalGroup(
            menuEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuEmpresasLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(menuEmpresasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnmenu7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlEmpresas.add(menuEmpresas, java.awt.BorderLayout.PAGE_START);

        tablaEmpresas.setPreferredSize(new java.awt.Dimension(1245, 530));

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "RUC Empresa", "Nombre Empresa", "Color", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTable7);

        EmpresasBotones.setEnabled(false);
        EmpresasBotones.setPreferredSize(new java.awt.Dimension(900, 216));
        EmpresasBotones.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                EmpresasBotonesComponentAdded(evt);
            }
        });
        EmpresasBotones.setLayout(new java.awt.BorderLayout());

        txtBuscar7.setMinimumSize(new java.awt.Dimension(650, 30));
        txtBuscar7.setPreferredSize(new java.awt.Dimension(450, 30));
        txtBuscar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscar7ActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlBotonesBusqueda7Layout = new javax.swing.GroupLayout(pnlBotonesBusqueda7);
        pnlBotonesBusqueda7.setLayout(pnlBotonesBusqueda7Layout);
        pnlBotonesBusqueda7Layout.setHorizontalGroup(
            pnlBotonesBusqueda7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesBusqueda7Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(txtBuscar7, javax.swing.GroupLayout.PREFERRED_SIZE, 827, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(366, Short.MAX_VALUE))
        );
        pnlBotonesBusqueda7Layout.setVerticalGroup(
            pnlBotonesBusqueda7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesBusqueda7Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(pnlBotonesBusqueda7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlBotonesBusqueda7Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtBuscar7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        EmpresasBotones.add(pnlBotonesBusqueda7, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout tablaEmpresasLayout = new javax.swing.GroupLayout(tablaEmpresas);
        tablaEmpresas.setLayout(tablaEmpresasLayout);
        tablaEmpresasLayout.setHorizontalGroup(
            tablaEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EmpresasBotones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1237, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablaEmpresasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7)
                .addContainerGap())
        );
        tablaEmpresasLayout.setVerticalGroup(
            tablaEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablaEmpresasLayout.createSequentialGroup()
                .addComponent(EmpresasBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlEmpresas.add(tablaEmpresas, java.awt.BorderLayout.CENTER);

        paneles.add(pnlEmpresas, "card2");

        pnlUnidades.setLayout(new java.awt.BorderLayout());

        menuUnidades.setAlignmentX(1.0F);
        menuUnidades.setPreferredSize(new java.awt.Dimension(100, 80));

        btnmenu8.setBackground(new java.awt.Color(30, 30, 30));
        btnmenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/menu.png"))); // NOI18N
        btnmenu8.setPreferredSize(new java.awt.Dimension(120, 123));
        btnmenu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenu8ActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Unidades");
        jLabel39.setAlignmentX(1.0F);
        jLabel39.setPreferredSize(new java.awt.Dimension(262, 40));

        javax.swing.GroupLayout menuUnidadesLayout = new javax.swing.GroupLayout(menuUnidades);
        menuUnidades.setLayout(menuUnidadesLayout);
        menuUnidadesLayout.setHorizontalGroup(
            menuUnidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuUnidadesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnmenu8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(892, Short.MAX_VALUE))
        );
        menuUnidadesLayout.setVerticalGroup(
            menuUnidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuUnidadesLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(menuUnidadesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnmenu8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlUnidades.add(menuUnidades, java.awt.BorderLayout.PAGE_START);

        tablaUnidades.setPreferredSize(new java.awt.Dimension(1245, 530));

        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código de Unidad", "Código de SOAT", "ID de Ruta", "DNI", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane8.setViewportView(jTable8);

        UnidadesBotones.setEnabled(false);
        UnidadesBotones.setPreferredSize(new java.awt.Dimension(900, 216));
        UnidadesBotones.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                UnidadesBotonesComponentAdded(evt);
            }
        });
        UnidadesBotones.setLayout(new java.awt.BorderLayout());

        txtBuscar8.setMinimumSize(new java.awt.Dimension(650, 30));
        txtBuscar8.setPreferredSize(new java.awt.Dimension(450, 30));
        txtBuscar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscar8ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout pnlBotonesBusqueda8Layout = new javax.swing.GroupLayout(pnlBotonesBusqueda8);
        pnlBotonesBusqueda8.setLayout(pnlBotonesBusqueda8Layout);
        pnlBotonesBusqueda8Layout.setHorizontalGroup(
            pnlBotonesBusqueda8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesBusqueda8Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(txtBuscar8, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(239, Short.MAX_VALUE))
        );
        pnlBotonesBusqueda8Layout.setVerticalGroup(
            pnlBotonesBusqueda8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesBusqueda8Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(pnlBotonesBusqueda8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBuscar8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        UnidadesBotones.add(pnlBotonesBusqueda8, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout tablaUnidadesLayout = new javax.swing.GroupLayout(tablaUnidades);
        tablaUnidades.setLayout(tablaUnidadesLayout);
        tablaUnidadesLayout.setHorizontalGroup(
            tablaUnidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UnidadesBotones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1237, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablaUnidadesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8)
                .addContainerGap())
        );
        tablaUnidadesLayout.setVerticalGroup(
            tablaUnidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablaUnidadesLayout.createSequentialGroup()
                .addComponent(UnidadesBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlUnidades.add(tablaUnidades, java.awt.BorderLayout.CENTER);

        paneles.add(pnlUnidades, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneles, javax.swing.GroupLayout.DEFAULT_SIZE, 1297, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenu5ActionPerformed
        Drawer.getInstance().showDrawer();
    }//GEN-LAST:event_btnmenu5ActionPerformed

    private void txtBuscar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscar5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscar5ActionPerformed

    private void ConsumoBotonesComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_ConsumoBotonesComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsumoBotonesComponentAdded

    private void btnmenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenu6ActionPerformed
        Drawer.getInstance().showDrawer();
    }//GEN-LAST:event_btnmenu6ActionPerformed

    private void txtBuscar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscar6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscar6ActionPerformed

    private void RutasBotonesComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_RutasBotonesComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_RutasBotonesComponentAdded

    private void btnmenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenu7ActionPerformed
        Drawer.getInstance().showDrawer();
    }//GEN-LAST:event_btnmenu7ActionPerformed

    private void txtBuscar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscar7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscar7ActionPerformed

    private void EmpresasBotonesComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_EmpresasBotonesComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpresasBotonesComponentAdded

    private void btnmenu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenu8ActionPerformed
        Drawer.getInstance().showDrawer();
    }//GEN-LAST:event_btnmenu8ActionPerformed

    private void txtBuscar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscar8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscar8ActionPerformed

    private void UnidadesBotonesComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_UnidadesBotonesComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_UnidadesBotonesComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Color color = Color.decode("#5856D6");
        FlatRobotoFont.install();
        FlatLaf.registerCustomDefaultsSource("Temas");
        UIManager.put("defaultFont", new Font(FlatRobotoFont.FAMILY, Font.PLAIN, 13));
        UIManager.put("Button.background", color);
        FlatMacDarkLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaConductor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public Clases.CrazyPanel ConsumoBotones;
    public Clases.CrazyPanel EmpresasBotones;
    public Clases.CrazyPanel RutasBotones;
    public Clases.CrazyPanel UnidadesBotones;
    private javax.swing.JButton btnmenu5;
    private javax.swing.JButton btnmenu6;
    private javax.swing.JButton btnmenu7;
    private javax.swing.JButton btnmenu8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable8;
    private javax.swing.JLabel jlblnombreusuario;
    private Clases.CrazyPanel menuConsumos;
    private Clases.CrazyPanel menuEmpresas;
    private Clases.CrazyPanel menuRutas;
    private Clases.CrazyPanel menuUnidades;
    public raven.crazypanel.CrazyPanel paneles;
    private Clases.CrazyPanel pnlBotonesBusqueda5;
    private Clases.CrazyPanel pnlBotonesBusqueda6;
    private Clases.CrazyPanel pnlBotonesBusqueda7;
    private Clases.CrazyPanel pnlBotonesBusqueda8;
    public raven.crazypanel.CrazyPanel pnlConsumos;
    public raven.crazypanel.CrazyPanel pnlEmpresas;
    public raven.crazypanel.CrazyPanel pnlRutas;
    public raven.crazypanel.CrazyPanel pnlUnidades;
    public Clases.CrazyPanel tablaConsumos;
    public Clases.CrazyPanel tablaEmpresas;
    public Clases.CrazyPanel tablaRutas;
    public Clases.CrazyPanel tablaUnidades;
    public javax.swing.JTable tblconsumosuser;
    public javax.swing.JTable tblrutas;
    private javax.swing.JTextField txtBuscar5;
    private javax.swing.JTextField txtBuscar6;
    private javax.swing.JTextField txtBuscar7;
    private javax.swing.JTextField txtBuscar8;
    // End of variables declaration//GEN-END:variables
}
