/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Cajon.ConstructorCajonUsuario;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.awt.Color;
import java.awt.Font;
import javax.swing.UIManager;
import raven.drawer.Drawer;
import raven.popup.GlassPanePopup;

/**
 *
 * @author abela
 */
public class VistaUsuario extends javax.swing.JFrame {

    /**
     * Creates new form VistaUsuario
     */
    public VistaUsuario() {
        GlassPanePopup.install(this);
        ConstructorCajonUsuario constructorCajonUsuario = new ConstructorCajonUsuario(this);
        Drawer.getInstance().setDrawerBuilder(constructorCajonUsuario);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneles = new raven.crazypanel.CrazyPanel();
        pnlTarjetas = new raven.crazypanel.CrazyPanel();
        menuTarjetas = new Clases.CrazyPanel();
        btnmenu3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tablaTarjetas = new Clases.CrazyPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        TarjetaBotones = new Clases.CrazyPanel();
        pnlBotonesBusqueda3 = new Clases.CrazyPanel();
        txtBuscar3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pnlRecargas = new raven.crazypanel.CrazyPanel();
        menuRecargas = new Clases.CrazyPanel();
        btnmenu4 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        tablaRecargas = new Clases.CrazyPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        RecargaBotones = new Clases.CrazyPanel();
        pnlRecargasForm = new Clases.CrazyPanel();
        pnlRecargasForm1 = new Clases.CrazyPanel();
        jLabel22 = new javax.swing.JLabel();
        txtRecargatarjetaUsuario = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        montoRecargausuario = new javax.swing.JTextField();
        pnlBotonesBusqueda4 = new Clases.CrazyPanel();
        txtBuscar4 = new javax.swing.JTextField();
        btnRecargar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pnlConsumos = new raven.crazypanel.CrazyPanel();
        menuConsumos = new Clases.CrazyPanel();
        btnmenu5 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        tablaConsumos = new Clases.CrazyPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        ConsumoBotones = new Clases.CrazyPanel();
        pnlBotonesBusqueda5 = new Clases.CrazyPanel();
        txtBuscar5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paneles.setLayout(new java.awt.CardLayout(30, 20));

        pnlTarjetas.setLayout(new java.awt.BorderLayout());

        menuTarjetas.setAlignmentX(1.0F);
        menuTarjetas.setPreferredSize(new java.awt.Dimension(100, 80));

        btnmenu3.setBackground(new java.awt.Color(30, 30, 30));
        btnmenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/menu.png"))); // NOI18N
        btnmenu3.setPreferredSize(new java.awt.Dimension(120, 123));
        btnmenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenu3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tarjetas");
        jLabel2.setAlignmentX(1.0F);
        jLabel2.setPreferredSize(new java.awt.Dimension(262, 40));

        javax.swing.GroupLayout menuTarjetasLayout = new javax.swing.GroupLayout(menuTarjetas);
        menuTarjetas.setLayout(menuTarjetasLayout);
        menuTarjetasLayout.setHorizontalGroup(
            menuTarjetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuTarjetasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnmenu3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(900, Short.MAX_VALUE))
        );
        menuTarjetasLayout.setVerticalGroup(
            menuTarjetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuTarjetasLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(menuTarjetasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnmenu3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlTarjetas.add(menuTarjetas, java.awt.BorderLayout.PAGE_START);

        tablaTarjetas.setPreferredSize(new java.awt.Dimension(1245, 530));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cod Tarjeta", "Emisión", "Caducidad", "DNI", "Saldo", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        TarjetaBotones.setEnabled(false);
        TarjetaBotones.setPreferredSize(new java.awt.Dimension(900, 216));
        TarjetaBotones.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TarjetaBotonesComponentAdded(evt);
            }
        });
        TarjetaBotones.setLayout(new java.awt.BorderLayout());

        txtBuscar3.setMinimumSize(new java.awt.Dimension(650, 30));
        txtBuscar3.setPreferredSize(new java.awt.Dimension(450, 30));
        txtBuscar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscar3ActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlBotonesBusqueda3Layout = new javax.swing.GroupLayout(pnlBotonesBusqueda3);
        pnlBotonesBusqueda3.setLayout(pnlBotonesBusqueda3Layout);
        pnlBotonesBusqueda3Layout.setHorizontalGroup(
            pnlBotonesBusqueda3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesBusqueda3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(txtBuscar3, javax.swing.GroupLayout.PREFERRED_SIZE, 964, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(235, Short.MAX_VALUE))
        );
        pnlBotonesBusqueda3Layout.setVerticalGroup(
            pnlBotonesBusqueda3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesBusqueda3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(pnlBotonesBusqueda3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBuscar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        TarjetaBotones.add(pnlBotonesBusqueda3, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout tablaTarjetasLayout = new javax.swing.GroupLayout(tablaTarjetas);
        tablaTarjetas.setLayout(tablaTarjetasLayout);
        tablaTarjetasLayout.setHorizontalGroup(
            tablaTarjetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TarjetaBotones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1245, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablaTarjetasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        tablaTarjetasLayout.setVerticalGroup(
            tablaTarjetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablaTarjetasLayout.createSequentialGroup()
                .addComponent(TarjetaBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pnlTarjetas.add(tablaTarjetas, java.awt.BorderLayout.CENTER);

        paneles.add(pnlTarjetas, "card2");

        pnlRecargas.setLayout(new java.awt.BorderLayout());

        menuRecargas.setAlignmentX(1.0F);
        menuRecargas.setPreferredSize(new java.awt.Dimension(100, 80));

        btnmenu4.setBackground(new java.awt.Color(30, 30, 30));
        btnmenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/menu.png"))); // NOI18N
        btnmenu4.setPreferredSize(new java.awt.Dimension(120, 123));
        btnmenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenu4ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Recargas");
        jLabel18.setAlignmentX(1.0F);
        jLabel18.setPreferredSize(new java.awt.Dimension(262, 40));

        javax.swing.GroupLayout menuRecargasLayout = new javax.swing.GroupLayout(menuRecargas);
        menuRecargas.setLayout(menuRecargasLayout);
        menuRecargasLayout.setHorizontalGroup(
            menuRecargasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuRecargasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnmenu4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(892, Short.MAX_VALUE))
        );
        menuRecargasLayout.setVerticalGroup(
            menuRecargasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuRecargasLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(menuRecargasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnmenu4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlRecargas.add(menuRecargas, java.awt.BorderLayout.PAGE_START);

        tablaRecargas.setPreferredSize(new java.awt.Dimension(1245, 530));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo de Recarga", "Tarjeta", "Monto de Recarga", "Fecha de Recarga", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        RecargaBotones.setEnabled(false);
        RecargaBotones.setPreferredSize(new java.awt.Dimension(900, 216));
        RecargaBotones.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                RecargaBotonesComponentAdded(evt);
            }
        });
        RecargaBotones.setLayout(new java.awt.BorderLayout());

        pnlRecargasForm.setMinimumSize(new java.awt.Dimension(1220, 200));
        pnlRecargasForm.setPreferredSize(new java.awt.Dimension(1217, 146));
        pnlRecargasForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRecargasForm1.setPreferredSize(new java.awt.Dimension(200, 200));
        pnlRecargasForm1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setText("N\" de Tarjeta");
        pnlRecargasForm1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        txtRecargatarjetaUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRecargatarjetaUsuarioKeyTyped(evt);
            }
        });
        pnlRecargasForm1.add(txtRecargatarjetaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 280, -1));

        jLabel25.setText("Monto");
        pnlRecargasForm1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, -1));

        montoRecargausuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montoRecargausuarioActionPerformed(evt);
            }
        });
        montoRecargausuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                montoRecargausuarioKeyTyped(evt);
            }
        });
        pnlRecargasForm1.add(montoRecargausuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 280, -1));

        pnlRecargasForm.add(pnlRecargasForm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 340, 160));

        RecargaBotones.add(pnlRecargasForm, java.awt.BorderLayout.CENTER);

        txtBuscar4.setMinimumSize(new java.awt.Dimension(650, 30));
        txtBuscar4.setPreferredSize(new java.awt.Dimension(450, 30));
        txtBuscar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscar4ActionPerformed(evt);
            }
        });

        btnRecargar.setText("Recargar");
        btnRecargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecargarMouseClicked(evt);
            }
        });
        btnRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlBotonesBusqueda4Layout = new javax.swing.GroupLayout(pnlBotonesBusqueda4);
        pnlBotonesBusqueda4.setLayout(pnlBotonesBusqueda4Layout);
        pnlBotonesBusqueda4Layout.setHorizontalGroup(
            pnlBotonesBusqueda4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesBusqueda4Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(txtBuscar4, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 400, Short.MAX_VALUE)
                .addComponent(btnRecargar)
                .addGap(17, 17, 17))
        );
        pnlBotonesBusqueda4Layout.setVerticalGroup(
            pnlBotonesBusqueda4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesBusqueda4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBotonesBusqueda4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlBotonesBusqueda4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRecargar)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        RecargaBotones.add(pnlBotonesBusqueda4, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout tablaRecargasLayout = new javax.swing.GroupLayout(tablaRecargas);
        tablaRecargas.setLayout(tablaRecargasLayout);
        tablaRecargasLayout.setHorizontalGroup(
            tablaRecargasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RecargaBotones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1237, Short.MAX_VALUE)
            .addComponent(jScrollPane4)
        );
        tablaRecargasLayout.setVerticalGroup(
            tablaRecargasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablaRecargasLayout.createSequentialGroup()
                .addComponent(RecargaBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlRecargas.add(tablaRecargas, java.awt.BorderLayout.CENTER);

        paneles.add(pnlRecargas, "card2");

        pnlConsumos.setLayout(new java.awt.BorderLayout());

        menuConsumos.setAlignmentX(1.0F);
        menuConsumos.setPreferredSize(new java.awt.Dimension(100, 80));

        btnmenu5.setBackground(new java.awt.Color(30, 30, 30));
        btnmenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/menu.png"))); // NOI18N
        btnmenu5.setPreferredSize(new java.awt.Dimension(120, 123));
        btnmenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenu5ActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Consumos");
        jLabel26.setAlignmentX(1.0F);
        jLabel26.setPreferredSize(new java.awt.Dimension(262, 40));

        javax.swing.GroupLayout menuConsumosLayout = new javax.swing.GroupLayout(menuConsumos);
        menuConsumos.setLayout(menuConsumosLayout);
        menuConsumosLayout.setHorizontalGroup(
            menuConsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuConsumosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnmenu5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(892, Short.MAX_VALUE))
        );
        menuConsumosLayout.setVerticalGroup(
            menuConsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuConsumosLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(menuConsumosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnmenu5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlConsumos.add(menuConsumos, java.awt.BorderLayout.PAGE_START);

        tablaConsumos.setPreferredSize(new java.awt.Dimension(1245, 530));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código de Consumo", "Tarjeta", "Monto de Consumo", "Fecha de Consumo", "Unidad", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable5);

        ConsumoBotones.setEnabled(false);
        ConsumoBotones.setPreferredSize(new java.awt.Dimension(900, 216));
        ConsumoBotones.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                ConsumoBotonesComponentAdded(evt);
            }
        });
        ConsumoBotones.setLayout(new java.awt.BorderLayout());

        txtBuscar5.setMinimumSize(new java.awt.Dimension(650, 30));
        txtBuscar5.setPreferredSize(new java.awt.Dimension(450, 30));
        txtBuscar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscar5ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlBotonesBusqueda5Layout = new javax.swing.GroupLayout(pnlBotonesBusqueda5);
        pnlBotonesBusqueda5.setLayout(pnlBotonesBusqueda5Layout);
        pnlBotonesBusqueda5Layout.setHorizontalGroup(
            pnlBotonesBusqueda5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesBusqueda5Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(txtBuscar5, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(304, Short.MAX_VALUE))
        );
        pnlBotonesBusqueda5Layout.setVerticalGroup(
            pnlBotonesBusqueda5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesBusqueda5Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(pnlBotonesBusqueda5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBuscar5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        ConsumoBotones.add(pnlBotonesBusqueda5, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout tablaConsumosLayout = new javax.swing.GroupLayout(tablaConsumos);
        tablaConsumos.setLayout(tablaConsumosLayout);
        tablaConsumosLayout.setHorizontalGroup(
            tablaConsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ConsumoBotones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1237, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablaConsumosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        tablaConsumosLayout.setVerticalGroup(
            tablaConsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablaConsumosLayout.createSequentialGroup()
                .addComponent(ConsumoBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlConsumos.add(tablaConsumos, java.awt.BorderLayout.CENTER);

        paneles.add(pnlConsumos, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneles, javax.swing.GroupLayout.DEFAULT_SIZE, 1297, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnmenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenu3ActionPerformed
        Drawer.getInstance().showDrawer();
    }//GEN-LAST:event_btnmenu3ActionPerformed

    private void txtBuscar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscar3ActionPerformed

    private void TarjetaBotonesComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TarjetaBotonesComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TarjetaBotonesComponentAdded

    private void btnmenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenu4ActionPerformed
        Drawer.getInstance().showDrawer();
    }//GEN-LAST:event_btnmenu4ActionPerformed

    private void montoRecargausuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montoRecargausuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montoRecargausuarioActionPerformed

    private void txtBuscar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscar4ActionPerformed

    private void btnRecargarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecargarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecargarMouseClicked

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecargarActionPerformed

    private void RecargaBotonesComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_RecargaBotonesComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_RecargaBotonesComponentAdded

    private void btnmenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenu5ActionPerformed
        Drawer.getInstance().showDrawer();
    }//GEN-LAST:event_btnmenu5ActionPerformed

    private void txtBuscar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscar5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscar5ActionPerformed

    private void ConsumoBotonesComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_ConsumoBotonesComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsumoBotonesComponentAdded

    private void txtRecargatarjetaUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRecargatarjetaUsuarioKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;

        if (!(numeros)) {
            evt.consume(); // Consumir el evento para evitar que se procese
        }
        if (txtRecargatarjetaUsuario.getText().length() >= 16) {
            evt.consume(); // Consumir el evento para evitar que se procese
        }
    }//GEN-LAST:event_txtRecargatarjetaUsuarioKeyTyped

    private void montoRecargausuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_montoRecargausuarioKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;

        if (!(numeros)) {
            evt.consume(); // Consumir el evento para evitar que se procese
        }
        if (montoRecargausuario.getText().length() >= 16) {
            evt.consume(); // Consumir el evento para evitar que se proceso
        }
    }//GEN-LAST:event_montoRecargausuarioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Color color = Color.decode("#5856D6");
        FlatRobotoFont.install();
        FlatLaf.registerCustomDefaultsSource("Temas");
        UIManager.put("defaultFont", new Font(FlatRobotoFont.FAMILY, Font.PLAIN, 13));
        UIManager.put("Button.background", color);
        FlatMacDarkLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaUsuario().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public Clases.CrazyPanel ConsumoBotones;
    public Clases.CrazyPanel RecargaBotones;
    public Clases.CrazyPanel TarjetaBotones;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JButton btnmenu3;
    private javax.swing.JButton btnmenu4;
    private javax.swing.JButton btnmenu5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private Clases.CrazyPanel menuConsumos;
    private Clases.CrazyPanel menuRecargas;
    private Clases.CrazyPanel menuTarjetas;
    private javax.swing.JTextField montoRecargausuario;
    public raven.crazypanel.CrazyPanel paneles;
    private Clases.CrazyPanel pnlBotonesBusqueda3;
    private Clases.CrazyPanel pnlBotonesBusqueda4;
    private Clases.CrazyPanel pnlBotonesBusqueda5;
    public raven.crazypanel.CrazyPanel pnlConsumos;
    public raven.crazypanel.CrazyPanel pnlRecargas;
    private Clases.CrazyPanel pnlRecargasForm;
    private Clases.CrazyPanel pnlRecargasForm1;
    public raven.crazypanel.CrazyPanel pnlTarjetas;
    public Clases.CrazyPanel tablaConsumos;
    public Clases.CrazyPanel tablaRecargas;
    public Clases.CrazyPanel tablaTarjetas;
    private javax.swing.JTextField txtBuscar3;
    private javax.swing.JTextField txtBuscar4;
    private javax.swing.JTextField txtBuscar5;
    private javax.swing.JTextField txtRecargatarjetaUsuario;
    // End of variables declaration//GEN-END:variables
}
