/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Cajon.ConstructorCajonUsuario;
import Cajon.ConstructorCajon;
import Controladores.ControladorEmpresaTransporte;
import Controladores.ControladorPersonas;
import Controladores.ControladorRutas;
import Controladores.*;
import Controladores.ControladorUnidades;
import Controladores.ControladorUsuarios;
import Controladores.Rellenarcombo;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import conexion.Conexion;
import java.sql.Connection;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.util.List;
import java.util.Properties;
import javax.mail.Authenticator;
import javax.mail.BodyPart;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import modelos.*;
import modelos.EmpresaTransporteDAO;
import modelos.Personas;
import modelos.PersonasDAO;
import modelos.Rutas;
import modelos.RutasDAO;
import modelos.TarjetaDAO;
import modelos.Tarjetas;
import modelos.UnidadDAO;
import modelos.Unidades;
import modelos.UsuarioDAO;
import modelos.Usuarios;
import net.miginfocom.swing.MigLayout;
import raven.drawer.Drawer;
import raven.popup.GlassPanePopup;

import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

import java.util.Properties;
import javax.mail.*;
import javax.mail.internet.*;

import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.activation.FileDataSource;
import javax.management.Notification;
import javax.swing.JFileChooser;
import raven.toast.Notifications;

/**
 *
 * @author abela
 */
public class VistaUsuario extends javax.swing.JFrame {

    private Rellenarcombo rellenarcombo;
    private RegistroRecargas registroRecargas;
    private RegistroRecargasDAO registroRecargasDAO;
    private Personas user;
    private PersonasDAO perdao;
    public VistaUsuario() {
        GlassPanePopup.install(this);
        ConstructorCajonUsuario constructorCajonUsuario = new ConstructorCajonUsuario(this);
        Drawer.getInstance().setDrawerBuilder(constructorCajonUsuario);

        initComponents();
    }

    public VistaUsuario(String dni) {
        GlassPanePopup.install(this);
        ConstructorCajonUsuario constructorCajonUsuario = new ConstructorCajonUsuario(this);
        Drawer.getInstance().setDrawerBuilder(constructorCajonUsuario);
        initComponents();
        rellenarcombo=new Rellenarcombo();
        rellenarcombo.rellenarTarjetasEnComboBox(dni, cbxCodTarjetaRecarga);
        registroRecargasDAO= new RegistroRecargasDAO();
        registroRecargas= new RegistroRecargas();
        perdao=new PersonasDAO();
        user = perdao.persona(dni);
        ControladorVistaUsuario cintrio=new ControladorVistaUsuario(registroRecargasDAO, registroRecargas, this, dni);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneles = new raven.crazypanel.CrazyPanel();
        pnlRecargas = new raven.crazypanel.CrazyPanel();
        menuRecargas1 = new Clases.CrazyPanel();
        btnmenu6 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        tablaRecargas1 = new Clases.CrazyPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblRecargas = new javax.swing.JTable();
        RecargaBotones1 = new Clases.CrazyPanel();
        pnlRecargasForm2 = new Clases.CrazyPanel();
        pnlRecargasForm3 = new Clases.CrazyPanel();
        pnlRecargasForm4 = new Clases.CrazyPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        txtmontorecarga = new javax.swing.JTextField();
        cbxCodTarjetaRecarga = new javax.swing.JComboBox<>();
        btnVerTicket = new javax.swing.JButton();
        jLabel66 = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        btnRegistrarRecarga = new javax.swing.JButton();
        pnlBotonesBusqueda6 = new Clases.CrazyPanel();
        txtBuscar6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paneles.setLayout(new java.awt.CardLayout(30, 20));

        pnlRecargas.setLayout(new java.awt.BorderLayout());

        menuRecargas1.setAlignmentX(1.0F);
        menuRecargas1.setPreferredSize(new java.awt.Dimension(100, 80));

        btnmenu6.setBackground(new java.awt.Color(30, 30, 30));
        btnmenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/menu.png"))); // NOI18N
        btnmenu6.setPreferredSize(new java.awt.Dimension(120, 123));
        btnmenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenu6ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Recargas");
        jLabel19.setAlignmentX(1.0F);
        jLabel19.setPreferredSize(new java.awt.Dimension(262, 40));

        javax.swing.GroupLayout menuRecargas1Layout = new javax.swing.GroupLayout(menuRecargas1);
        menuRecargas1.setLayout(menuRecargas1Layout);
        menuRecargas1Layout.setHorizontalGroup(
            menuRecargas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuRecargas1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnmenu6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(900, Short.MAX_VALUE))
        );
        menuRecargas1Layout.setVerticalGroup(
            menuRecargas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuRecargas1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(menuRecargas1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnmenu6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlRecargas.add(menuRecargas1, java.awt.BorderLayout.PAGE_START);

        tablaRecargas1.setPreferredSize(new java.awt.Dimension(1245, 530));
        tablaRecargas1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblRecargas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo de Recarga", "Monto de Recarga", "Tarjeta", "Fecha de Recarga", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tblRecargas);

        tablaRecargas1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 244, 1245, 350));

        RecargaBotones1.setEnabled(false);
        RecargaBotones1.setPreferredSize(new java.awt.Dimension(900, 216));
        RecargaBotones1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                RecargaBotones1ComponentAdded(evt);
            }
        });
        RecargaBotones1.setLayout(new java.awt.BorderLayout());

        pnlRecargasForm2.setMinimumSize(new java.awt.Dimension(1220, 200));
        pnlRecargasForm2.setPreferredSize(new java.awt.Dimension(1217, 146));
        pnlRecargasForm2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRecargasForm3.setPreferredSize(new java.awt.Dimension(200, 200));
        pnlRecargasForm3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlRecargasForm2.add(pnlRecargasForm3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 340, 160));

        pnlRecargasForm4.setPreferredSize(new java.awt.Dimension(200, 200));
        pnlRecargasForm4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setText("N\" de Tarjeta");
        pnlRecargasForm4.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel53.setText("Monto");
        pnlRecargasForm4.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, -1));

        txtmontorecarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmontorecargaActionPerformed(evt);
            }
        });
        txtmontorecarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmontorecargaKeyTyped(evt);
            }
        });
        pnlRecargasForm4.add(txtmontorecarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 280, -1));

        pnlRecargasForm4.add(cbxCodTarjetaRecarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 280, -1));

        pnlRecargasForm2.add(pnlRecargasForm4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 340, 160));

        btnVerTicket.setText("Ver Ticket");
        btnVerTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTicketActionPerformed(evt);
            }
        });
        pnlRecargasForm2.add(btnVerTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 130, 40));

        jLabel66.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel66.setText("Enviar ticket a tu Email");
        pnlRecargasForm2.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 160, 30));

        btnEnviar.setText("Enviar Ticket ");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        pnlRecargasForm2.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 150, 40));

        btnRegistrarRecarga.setText("Recargar");
        btnRegistrarRecarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarRecargaActionPerformed(evt);
            }
        });
        pnlRecargasForm2.add(btnRegistrarRecarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 60, -1, -1));

        RecargaBotones1.add(pnlRecargasForm2, java.awt.BorderLayout.CENTER);

        pnlBotonesBusqueda6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar6.setMinimumSize(new java.awt.Dimension(650, 30));
        txtBuscar6.setPreferredSize(new java.awt.Dimension(450, 30));
        txtBuscar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscar6ActionPerformed(evt);
            }
        });
        pnlBotonesBusqueda6.add(txtBuscar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        RecargaBotones1.add(pnlBotonesBusqueda6, java.awt.BorderLayout.PAGE_START);

        tablaRecargas1.add(RecargaBotones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1245, -1));

        pnlRecargas.add(tablaRecargas1, java.awt.BorderLayout.CENTER);

        paneles.add(pnlRecargas, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneles, javax.swing.GroupLayout.PREFERRED_SIZE, 1297, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnmenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenu6ActionPerformed
        Drawer.getInstance().showDrawer();
    }//GEN-LAST:event_btnmenu6ActionPerformed

    private void txtmontorecargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmontorecargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmontorecargaActionPerformed

    private void btnVerTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTicketActionPerformed
        try {

            Conexion con = new Conexion();
            Connection conn = con.crearConexion();

            // Compilar el archivo .jasper
            JasperReport jasperReport = JasperCompileManager.compileReport("src\\Reportes\\TicketRecarga.jrxml");

            // Paso 3: Llenar el informe con datos desde la base de datos.
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, conn);

            // Paso 4: Mostrar el informe (puedes exportarlo a diferentes formatos también).
            JasperViewer.viewReport(jasperPrint);

            // O exportarlo a PDF
            JasperExportManager.exportReportToPdfFile(jasperPrint, "src\\Reportes\\TicketRecarga.pdf");

            //return jasperPrint;
        } catch (JRException err) {
            err.printStackTrace();
            System.out.println("INGRESO AL CATCH ERROR");
            System.out.println("ERROR.... " + err);
            //return null;
        }
    }//GEN-LAST:event_btnVerTicketActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed

        /*enviarCorreo(
            "luchitozabalaga@outlook.es",
            "Ticket de Recarga - EtravelEase",
            "En el archivo pdf encontrara información de la recarga realizada en nuestro sistema EtravelEase",
            "C:\\Users\\LuisDev\\Documents\\TicketRecarga.pdf"
        );*/
        enviarCorreo(
                user.getCorreoElectronico(),
                "Ticket de Recarga - EtravelEase",
                "En el archivo pdf encontrara información de la recarga realizada en nuestro sistema EtravelEase",
                "src\\Reportes\\TicketRecarga.pdf"
        );
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void txtBuscar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscar6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscar6ActionPerformed

    private void RecargaBotones1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_RecargaBotones1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_RecargaBotones1ComponentAdded

    private void btnRegistrarRecargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarRecargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarRecargaActionPerformed

    private void txtmontorecargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmontorecargaKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;

        if (!(numeros)) {
            evt.consume(); // Consumir el evento para evitar que se procese
        }
        if (txtmontorecarga.getText().length() >= 3) {
            evt.consume(); // Consumir el evento para evitar que se procese

        }
    }//GEN-LAST:event_txtmontorecargaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Color color = Color.decode("#5856D6");
        FlatRobotoFont.install();
        FlatLaf.registerCustomDefaultsSource("Temas");
        UIManager.put("defaultFont", new Font(FlatRobotoFont.FAMILY, Font.PLAIN, 13));
        UIManager.put("Button.background", color);
        FlatMacDarkLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaUsuario().setVisible(true);

            }
        });
    }

    public static void enviarCorreo(String destinatario, String asunto, String cuerpo, String rutaArchivo) {

        // Configuración para el servidor SMTP de Outlook
        String host = "smtp.office365.com";
        String port = "587";
        String username = "luchitozabalaga@outlook.es";
        String password = "Jorgezabalag@90";
        System.out.println(destinatario);
        // Propiedades para la sesión
        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", host);
        props.put("mail.smtp.port", port);

        // Crear una sesión con autenticación
        Session session = Session.getInstance(props, new Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(username, password);
            }
        });

        try {
            // Crear un mensaje de correo
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(username));
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(destinatario));
            message.setSubject(asunto);

            // Crear el cuerpo del mensaje
            BodyPart messageBodyPart = new MimeBodyPart();
            messageBodyPart.setText(cuerpo);

            // Crear la parte adjunta para el archivo PDF
            MimeBodyPart attachmentPart = new MimeBodyPart();
            String filePath = rutaArchivo; // Reemplazar con la ruta del archivo PDF
            DataSource source = new FileDataSource(filePath);
            attachmentPart.setDataHandler(new DataHandler(source));
            attachmentPart.setFileName("TicketRecarga.pdf");

            // Combinar las partes del mensaje
            Multipart multipart = new MimeMultipart();
            multipart.addBodyPart(messageBodyPart);
            multipart.addBodyPart(attachmentPart);

            // Establecer el contenido del mensaje como la combinación de partes
            message.setContent(multipart);

            // Enviar el mensaje
            Transport.send(message);

            JOptionPane.showMessageDialog(null, "Email enviado correctamente!!!");

            System.out.println("Correo enviado correctamente.");

        } catch (MessagingException e) {
            e.printStackTrace();
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public Clases.CrazyPanel RecargaBotones1;
    private javax.swing.JButton btnEnviar;
    public javax.swing.JButton btnRegistrarRecarga;
    private javax.swing.JButton btnVerTicket;
    private javax.swing.JButton btnmenu6;
    public javax.swing.JComboBox<String> cbxCodTarjetaRecarga;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JScrollPane jScrollPane6;
    private Clases.CrazyPanel menuRecargas1;
    public raven.crazypanel.CrazyPanel paneles;
    private Clases.CrazyPanel pnlBotonesBusqueda6;
    public raven.crazypanel.CrazyPanel pnlRecargas;
    private Clases.CrazyPanel pnlRecargasForm2;
    private Clases.CrazyPanel pnlRecargasForm3;
    private Clases.CrazyPanel pnlRecargasForm4;
    public Clases.CrazyPanel tablaRecargas1;
    public javax.swing.JTable tblRecargas;
    private javax.swing.JTextField txtBuscar6;
    public javax.swing.JTextField txtmontorecarga;
    // End of variables declaration//GEN-END:variables
}
